### ISSUE TITLE
can't run the code

### ISSUE THREAD

**Issue by menomega** [MODDEDWARFARE/PPPwn_WRT#1]
i got this error 

PPPwn_WRT-main  main.zip
root@OpenWrt:~# cd PPPwn_WRT-main/
root@OpenWrt:~/PPPwn_WRT-main# ./run.sh
---
/root/PPPwn_WRT-main/pppwn_mips: line 1: syntax error: unexpected "("

**Comment by oubahell** [comment]
i tried it with Ubiquiti nanostation M5 -XM 
and Mikrotik rb941-2nd-tc
and they are work with MIPS
and the 2 of them i got 
...
root@OpenWrt:~/PPPwn_WRT-main# ./run.sh
---
/root/PPPwn_WRT-main/pppwn_mips: line 0: syntax error: unexpected word (expecting ")")


i think it will take more time to make it support more cpu's

**Comment by mark01975** [comment]
/root/PPPwn_WRT-main/pppwn_mips: line 1: syntax error: unexpected "("

can't run PPPwn_WRT

my router is an GL-AR150 that runs OpenWrt 23.05.0, r23497-6637af95aa

**Comment by menomega** [comment]
solved

**Comment by oubahell** [comment]
|       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 18.06.9, r8077-7cbbab7246
 -----------------------------------------------------
root@OpenWrt:~# cd PPPwn_WRT-main/
root@OpenWrt:~/PPPwn_WRT-main# ls
kill.sh          run.sh           stage1_1100.bin
pppwn_mips       settings.cfg     stage2_1100.bin
root@OpenWrt:~/PPPwn_WRT-main# ./run.sh
---
[+] PPPwn++ - PlayStation 4 PPPoE RCE by theflow
[+] args: interface=br-lan fw=1100 stage1=/root/PPPwn_WRT-main/stage1_1100.bin stage2=/root/PPPwn_WRT-main/stage2_1100.bin timeout=0 wait-after-pin=1 groom-delay=4 auto-retry=on no-wait-padi=off real_sleep=off

[+] STAGE 0: Initialization
[*] Waiting for PADI...
[*] Waiting for PADI...
[+] pppoe_softc: 0xffff9d824c011400
[+] Target MAC: c8:63:f1:3b:2d:f5
[+] Source MAC: 07:14:01:4c:82:9d
[+] AC cookie length: 4e0
[*] Sending PADO...
[*] Waiting for PADR...
[*] Sending PADS...
[*] Sending LCP configure request...
[*] Waiting for LCP configure ACK...
[*] Waiting for LCP configure request...
[*] Sending LCP configure ACK...
[*] Sending IPCP configure request...
[*] Waiting for IPCP configure ACK...
[*] Waiting for IPCP configure request...
[*] Sending IPCP configure NAK...
[*] Waiting for IPCP configure request...
[*] Sending IPCP configure ACK...
[*] Waiting for interface to be ready...
[+] Target IPv6: fe80::ca63:f1ff:fe3b:2df5
[+] Heap grooming...done

[+] STAGE 1: Memory corruption
libc++abi: terminating due to uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
Aborted
root@OpenWrt:~/PPPwn_WRT-main#





new error occured and i checked everything  
latest goldhen + latest code 
this is miktotik rb-941
